# Generated by Django 5.1.2 on 2024-11-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_morningnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='morningnotes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
